# Site settings
baseURL = "https://mattjmcnaughton.com/"
languageCode = "en-us"
paginate = "10"
theme = "mainroad"
title = "~/mattjmcnaughton/blog"
googleAnalytics = "UA-101845615-1"
disqusShortname = "mattjmcnaughton"

[Author]
  name = "Matt McNaughton"
  bio = "SE@Flatiron Health - Williams College '16 - hackNY '15"

[Params]
  readmore = true
  subtitle = "SE@Flatiron Health - Williams College '16 - hackNY '15"
  post_navigation = true
  postSections = ["post"]
  dateformat = "2006-01-02"

[Params.widgets]
  search = true
  categories = true
  tags_counter = true

  social_github = "mattjmcnaughton"
  social_email = "mattjmcnaughton@gmail.com"
