# Site settings
baseURL = "https://mattjmcnaughton.com/"
languageCode = "en-us"
paginate = "10"
theme = "mainroad"
title = "~/mattjmcnaughton/blog"

[Params]
  readmore = true
  post_navigation = true
  mainSections = ["post"]
  post_meta = ["date", "categories"]
  dateformat = "2006-01-02"
  highlightColor = "#95a5a6"

[Params.logo]
  image = "img/avatar/mattjmcnaughton-and-pug-typing-pixelated.png"

[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["social"]

[Params.widgets.social]
  github = "mattjmcnaughton"
  email = "me@mattjmcnaughton.com"

# Needed to render raw html
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
